### ISSUE TITLE
Finish the rapsberry pi install instructions

### ISSUE THREAD

**Issue by rlagerweij** [BorisBrock/Sunalyzer#74]
Hi there, great project and I would love to contribute a Goodwe backend for this. 

However, I would like to run this on bare metal linux rather than in a docker contrainer. Would it be possible to finish the manual install instructions in the readme? I assume the installation instructions on raspberry would mostly translate to other linux distributions as well.

**Comment by rlagerweij** [comment]
Just partially (and poorly) answer my own question, I can get Sunalyzer to run well enough on debian to develop on with the following commands:

$ apt install git python3-pip
$ git clone https://github.com/BorisBrock/Sunalyzer.git
$ cd ./Sunalyzer
$ pip install -r requirements.txt
$ mkdir data
$ cp templates/config.yml data/
$ python3 backend/grabber.py &
$ python3 backend/server.py &

**Comment by BorisBrock** [comment]
Hi @rlagerweij,
Sunalyzer does not need much to run. As you have already figured out, it basically requires Python 3 and some dependencies, that can be installed by using pip. After that you may need to edit the config file. Then just start the grabber and the server.

So was what you wrote above should work :+1:
