### ISSUE TITLE
Install on server to serve multiple users

### ISSUE THREAD

**Issue by test2a** [BorisBrock/Sunalyzer#77]
Hi

Just found the project and I have some questions.

1. Is it for resident home local hosting on a pi or can we install and use it over a vps also? I mean I guess we could anyway but is it designed that way ?

2. Can we have multiple users who have their own system data separate? Like I have a project in mind to set up a neighbourhood level network so that everyone can see their own generation and other details.

3. If we use the vps, would it be possible to send data from an esp8266/32 to the "server" meaning the actual hardware requirement is reduced ? We can just plug in the ESP to the router, give WiFi credentials and website api key or crendentials?

**Comment by BorisBrock** [comment]
Hi test2a,
this project was designed to be used on site. In theory it should be possible to run it on a remote VPS, but that would introduce several security implications. E.g. the communication between the server and the inverter would need to be secured by a VPN tunnel.
Also there is currently no user account management.

So what you have in mind would be rather difficult to set up.
